//An exception can be generated by one method and caught by another
public class ExTest {

	//Generate an exception
	static void genException()
	{
		int nums[]=new int[4];
		System.out.println("Before exception is generated.");
		//generate an index out of bound exception
		nums[7]=10;
		System.out.println("this wont be dispalyed");
	}
}
